"""empty message

Revision ID: 36dff352ce5e
Revises: 5732652e160d
Create Date: 2021-05-13 20:47:44.287588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36dff352ce5e'
down_revision = '5732652e160d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current', sa.Column('parents', sa.Integer(), nullable=False))
    op.drop_constraint('current_ibfk_1', 'current', type_='foreignkey')
    op.create_foreign_key(None, 'current', 'parent', ['parents'], ['id'])
    op.drop_column('current', 'parent_id')
    op.alter_column('parent', 'parent',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parent', 'parent',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('current', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'current', type_='foreignkey')
    op.create_foreign_key('current_ibfk_1', 'current', 'parent', ['parent_id'], ['id'])
    op.drop_column('current', 'parents')
    # ### end Alembic commands ###
