"""empty message

Revision ID: 88b936494663
Revises: 05ab5bdbab32
Create Date: 2021-05-10 17:09:37.672683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b936494663'
down_revision = '05ab5bdbab32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grandparent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('age'),
    sa.UniqueConstraint('age'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('reference'),
    sa.UniqueConstraint('reference')
    )
    op.add_column('current', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('current', sa.Column('age', sa.String(length=120), nullable=False))
    op.add_column('current', sa.Column('reference', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'current', ['age'])
    op.create_unique_constraint(None, 'current', ['lastname'])
    op.create_unique_constraint(None, 'current', ['reference'])
    op.drop_column('current', 'password')
    op.drop_column('current', 'is_active')
    op.add_column('parent', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('parent', sa.Column('age', sa.String(length=120), nullable=False))
    op.add_column('parent', sa.Column('reference', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'parent', ['reference'])
    op.create_unique_constraint(None, 'parent', ['lastname'])
    op.create_unique_constraint(None, 'parent', ['age'])
    op.drop_column('parent', 'password')
    op.drop_column('parent', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('parent', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'parent', type_='unique')
    op.drop_constraint(None, 'parent', type_='unique')
    op.drop_constraint(None, 'parent', type_='unique')
    op.drop_column('parent', 'reference')
    op.drop_column('parent', 'age')
    op.drop_column('parent', 'lastname')
    op.add_column('current', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('current', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'current', type_='unique')
    op.drop_constraint(None, 'current', type_='unique')
    op.drop_constraint(None, 'current', type_='unique')
    op.drop_column('current', 'reference')
    op.drop_column('current', 'age')
    op.drop_column('current', 'lastname')
    op.drop_table('grandparent')
    # ### end Alembic commands ###
